spring:
  datasource:
    url: jdbc:h2:file:/C:/development/Santander/Java/todo-list-novo/database
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
